### ISSUE TITLE
[FIX] E7-S1 카테고리 api 수정

### ISSUE THREAD

**Issue by nrudev** [INFP-Study/CIAT#98]
## 소요 시간

- 예상 완료 시간 : ~~1시간~~ 2시간
- 실제 투입 시간 :

## 진행 사항

- [x] isActivated 이름 변경
- [x] Category delete 방식 변경
- [x] Account 연관관계 설정
- [x] 카테고리 조회 시 메뉴id 가 아닌 메뉴 urlPath를 프론트엔드에서 받는 것으로 변경
- [x] 카테고리를 return 할 때 카테고리가 속한 메뉴명까지 return하도록 변경

**Comment by thyoondev** [comment]
컬럼명은 카멜케이스말고 스네이크케이스로 부탁드립니다!

**Comment by thyoondev** [comment]
> 컬럼명은 카멜케이스말고 스네이크케이스로 부탁드립니다!

디비 컬럼이욤

**Comment by nrudev** [comment]
> 컬럼명은 카멜케이스말고 스네이크케이스로 부탁드립니다!

JPA 자체적으로 카멜케이스를 DB에서 스네이크 케이스로 바꿔주는데 엔티티 클래스에서도 카멜 케이스 사용해야 하나요..? 코드 컨벤션에 어긋나는 거 같은데.

**Comment by thyoondev** [comment]
> > 컬럼명은 카멜케이스말고 스네이크케이스로 부탁드립니다!
> 
> JPA 자체적으로 카멜케이스를 DB에서 스네이크 케이스로 바꿔주는데 엔티티 클래스에서도 카멜 케이스 사용해야 하나요..? 코드 컨벤션에 어긋나는 거 같은데.

엔티티 클래스에서는 카멜케이스
디비에서는 스네이크케이스
그럼 지금 사항 그대로 진행하시면 될 것 같습니다~
SHOW_YN으로 변경전에 디비 컬럼명이 카멜케이스로 되어있어서 말씀드렸습니다😓😓
